[scrolling]
history = 100000

[keyboard]
bindings = [
  { key = "N", mods = "Command", action = "CreateNewWindow" }
]

[font]
size = 14
normal.family = "Iosevka Term"
# For some reason this is needed with Iosevka
normal.style = "Regular"

[window]
padding.x = 6
padding.y = 6

[colors.cursor]
background = '#00FF80'
text = '#004020'


[colors]
draw_bold_text_with_bright_colors = true



[colors.dim]
red = '#fd0000'
yellow = '#7e5e00'
green = '#007d1f'
cyan = '#007387'
blue = '#4000ff'
magenta = '#c900c8'
black = '#000000'
white = '#636363'

[colors.normal]
red = '#ff0054'
yellow = '#ef9900'
green = '#42d100'
cyan = '#00dee7'
blue = '#008fff'
magenta = '#e572ff'
black = '#222222'
white = '#aeaeae'

[colors.bright]
red = '#ff5a00'
yellow = '#c8b100'
green = '#00d48d'
cyan = '#00c8ff'
blue = '#a490ff'
magenta = '#ff54d2'
black = '#636363'
white = '#ffffff'

[colors.primary]
background = '#000000'
dim_foreground = '#636363'
foreground = '#aeaeae'
bright_foreground = '#ffffff'

