[scrolling]
history = 100000

[keyboard]
bindings = [
  { key = "N", mods = "Command", action = "CreateNewWindow" }
]

[font]
size = 14
normal.family = "Iosevka Term"
# For some reason this is needed with Iosevka
normal.style = "Regular"

[window]
padding.x = 6
padding.y = 6

[colors.cursor]
background = '#00FF80'
text = '#004020'


[colors]
draw_bold_text_with_bright_colors = true



[colors.dim]
black = '#000000'
red = '#fd0000'
green = '#008e00'
yellow = '#825c00'
blue = '#2300ff'
magenta = '#c200d8'
cyan = '#007584'
white = '#636363'

[colors.normal]
black = '#222222'
red = '#ff0071'
green = '#6acc00'
yellow = '#f59400'
blue = '#0099ff'
magenta = '#d97dff'
cyan = '#00ece7'
white = '#aeaeae'

[colors.bright]
black = '#636363'
red = '#ff4400'
green = '#00d57d'
yellow = '#cead00'
blue = '#968cff'
magenta = '#ff4ce2'
cyan = '#00cfff'
white = '#ffffff'

[colors.primary]
background = '#000000'
foreground = '#aeaeae'
dim_foreground = '#636363'
bright_foreground = '#ffffff'

